### PR TITLE
Update to latest

### PR DESCRIPTION
**Pull request by intech**
update node version
update docker-compose version
update traefik change args
add label for traefik
add network layer
remove links

### CODE REVIEW

**Comment by icebob** [comment]
Could you test it?

**Comment by intech** [comment]
> Could you test it?

Of course! You can repeat until merge:
```bash
moleculer alias-template intech intech/moleculer-template-project
moleculer init intech template-test
cd template-test
npm install
npm run dc:up
```

**Comment by intech** [comment]
I have not tested just kafka... one moment

**Comment by intech** [comment]
All works fine!

**Review by icebob — APPROVED** [review]
Great, thanks!

**Pull request merged**
