### PR TITLE
feature: add hot reload in Dockerfile for use in develop too

### PR DESCRIPTION
**Pull request by devalexandre**
In order to be able to use the same environment both in development and in production it is important that developers use the same versions of services, so I believe I have a docker-compose that can be used both in production and in development something crucial

### CODE REVIEW

**Comment by intech** [comment]
I think this is the wrong approach for a shared repository.

In any case, the container requires rebuilding the code or forwarding volume with the code from the host machine, otherwise there is no point in hot reloading.

You can use this template in your tasks from your repository via [custom](https://moleculer.services/docs/0.14/moleculer-cli.html#Custom-templates)

**Comment by devalexandre** [comment]
> I think this is the wrong approach for a shared repository.
> 
> In any case, the container requires rebuilding the code or forwarding volume with the code from the host machine, otherwise there is no point in hot reloading.
> 
> You can use this template in your tasks from your repository via [custom](https://moleculer.services/docs/0.14/moleculer-cli.html#Custom-templates)

yes it makes perfect sense, i sent a done placing the image inside the project so it looks better, i will keep the same image on the dockerhub and put the link here so i keep the travis for testing

**Review by devalexandre — COMMENTED** [review]
add image in Dockerfile

**Comment by icebob** [comment]
This template creates a common minimal project (with minimal docker image). So it's just a basic config, the users should  add more details. Your Dockerfile is a custom file for your use-case which is not common and minimal, so I won't merge it. Sry.

**Pull request closed without merging**
